codecov:
  branch: dev
  max_report_age: off

coverage:
  range: 45..100
  round: down
  precision: 5
  status:
    project:
      default:
        threshold: 10%
    patch:
      default:
        threshold: 95%

  ignore:
    - "docs/*"
    - "tests/*"

comment:
  layout: "header, diff, changes, sunburst, uncovered"
  behavior: default
