version: '3'

services:
  build:
    image: honeybadgermpc-local
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/HoneyBadgerMPC
      - /usr/src/HoneyBadgerMPC/honeybadgermpc/ntl  # Directory _not_ mounted from host
    environment:
      - O=-W --keep-going
    command: make -C docs html
  watch:
    image: honeybadgermpc-local
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/HoneyBadgerMPC
    environment:
      - O=-W --keep-going
    command: watchmedo shell-command -p '*.rst' -c 'make -C docs html' -R -D .
  view:
    image: nginx
    ports:
      - '58888:80'
    volumes:
      - ./docs/_build/html:/usr/share/nginx/html
