version: '3'

services:
  hbmpc_0:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/HoneyBadgerMPC
    environment:
      HBMPC_CONFIG: conf/ipc.network.docker/hbmpc_0.ini
    command: python -m honeybadgermpc.ipc
  hbmpc_1:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/HoneyBadgerMPC
    environment:
      HBMPC_CONFIG: conf/ipc.network.docker/hbmpc_1.ini
    command: python -m honeybadgermpc.ipc
  hbmpc_2:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/HoneyBadgerMPC
    environment:
      HBMPC_CONFIG: conf/ipc.network.docker/hbmpc_2.ini
    command: python -m honeybadgermpc.ipc
  hbmpc_3:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/HoneyBadgerMPC
    environment:
      HBMPC_CONFIG: conf/ipc.network.docker/hbmpc_3.ini
    command: python -m honeybadgermpc.ipc
