version: '3'

services:
  hbmpc_0:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/HoneyBadgerMPC
    environment:
      HBMPC_CONFIG: conf/ipc.network.docker/hbmpc.ini
    command: python -m honeybadgermpc.ipc 0
  hbmpc_1:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/HoneyBadgerMPC
    environment:
      HBMPC_CONFIG: conf/ipc.network.docker/hbmpc.ini
    command: python -m honeybadgermpc.ipc 1
  hbmpc_2:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/HoneyBadgerMPC
    environment:
      HBMPC_CONFIG: conf/ipc.network.docker/hbmpc.ini
    command: python -m honeybadgermpc.ipc 2
  hbmpc_3:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/HoneyBadgerMPC
    environment:
      HBMPC_CONFIG: conf/ipc.network.docker/hbmpc.ini
    command: python -m honeybadgermpc.ipc 3
