version: '3'

services:
  hbmpc_0:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/HoneyBadgerMPC
    environment:
      HBMPC_CONFIG: conf/ipc.network.docker/hbmpc.ini
      HBMPC_NODE_ID: 0
    command: python -m honeybadgermpc.ipc
  hbmpc_1:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/HoneyBadgerMPC
    environment:
      HBMPC_CONFIG: conf/ipc.network.docker/hbmpc.ini
      HBMPC_NODE_ID: 1
    command: python -m honeybadgermpc.ipc
  hbmpc_2:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/HoneyBadgerMPC
    environment:
      HBMPC_CONFIG: conf/ipc.network.docker/hbmpc.ini
      HBMPC_NODE_ID: 2
    command: python -m honeybadgermpc.ipc
  hbmpc_3:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/HoneyBadgerMPC
    environment:
      HBMPC_CONFIG: conf/ipc.network.docker/hbmpc.ini
      HBMPC_NODE_ID: 3
    command: python -m honeybadgermpc.ipc
